services:
  db:
    image: postgres:15-alpine
    container_name: sisreserva-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgeem-network

  openldap:
    image: osixia/openldap
    container_name: sisreserva-ldap
    profiles: [ "dev" ]
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "UECE"
      LDAP_DOMAIN: "uece.br"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - pgeem-network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: sisreserva-ldap-ui
    profiles: ["dev"]
    restart: always
    ports:
      - "6443:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - pgeem-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sisreserva-api
    restart: on-failure
    depends_on:
      - db
      - openldap
    ports:
      - "${SERVER_PORT:?ERROR: SERVER_PORT não definida no arquivo .env}:${SERVER_PORT}"
    env_file:
      - .env.docker
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:? SPRING_DATASOURCE_USERNAME não definida no arquivo .env}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:? SPRING_DATASOURCE_PASSWORD não definida no arquivo .env}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:? CORS_ALLOWED_ORIGINS não definida no arquivo .env}
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET:? API_SECURITY_TOKEN_SECRET não definida no arquivo .env}
      - API_SECURITY_ACCESS_SECRET=${API_SECURITY_ACCESS_SECRET:? API_SECURITY_ACCESS_SECRET não definida no arquivo .env}
      - API_SECURITY_REFRESH_SECRET=${API_SECURITY_REFRESH_SECRET:? API_SECURITY_REFRESH_SECRET não definida no arquivo .env}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:? SPRING_MAIL_HOST não definida no arquivo .env}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT:? SPRING_MAIL_PORT não definida no arquivo .env}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:? SPRING_MAIL_USERNAME não definida no arquivo .env}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:? SPRING_MAIL_PASSWORD não definida no arquivo .env}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:? SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH não definida no arquivo .env}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:? SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE não definida no arquivo .env}
      - LDAP_URL=${LDAP_URL}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE}
      - LDAP_USER_SEARCH_FILTER=${LDAP_USER_SEARCH_FILTER}
      - API_SECURITY_ONBOARDING_SECRET=${API_SECURITY_ONBOARDING_SECRET:? API_SECURITY_ONBOARDING_SECRET não definida no arquivo .env}
    networks:
      - pgeem-network

volumes:
  postgres_data:
  ldap_data:
  ldap_config:

networks:
  pgeem-network:
    name: pgeem-network