# Usar banco H2 só nos testes
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Desativa Flyway nos testes
spring.flyway.enabled=false

# Segredo do JWT para testes
api.security.access.secret=test-access-secret
api.security.refresh.secret=test-refresh-secret

cookie.secure=false

ldap.url=ldap://localhost:389
ldap.base-dn=dc=test,dc=local
ldap.bind-dn=cn=admin,dc=test,dc=local
ldap.bind-password=test
ldap.user-search-base=ou=users
ldap.user-search-filter=(sAMAccountName={0})
api.security.onboarding.secret=test-onboarding-secret