INSERT INTO dev.departamento (id, nome, created_at, updated_at) VALUES
(uuid_generate_v4(), 'Centro de Ciências da Saúde (CCS)', NOW(), NOW()),
(uuid_generate_v4(), 'Centro de Humanidades (CH)', NOW(), NOW()),
(uuid_generate_v4(), 'Centro de Ciências e Tecnologia (CCT)', NOW(), NOW()),
(uuid_generate_v4(), 'Centro de Educação (CED)', NOW(), NOW()),
(uuid_generate_v4(), 'Centro de Estudos Sociais Aplicados (CESA)', NOW(), NOW()),
(uuid_generate_v4(), 'Centro de Ciências Biológicas e da Saúde (CCBS)', NOW(), NOW()),
(uuid_generate_v4(), 'Faculdade de Veterinária (FAVET)', NOW(), NOW()),
(uuid_generate_v4(), 'Faculdade de Educação, Ciências e Letras (FECLI)', NOW(), NOW()),
(uuid_generate_v4(), 'Faculdade de Filosofia Dom Aureliano Matos (FAFIDAM)', NOW(), NOW()),
(uuid_generate_v4(), 'Instituto Superior de Ciências Biomédicas (ISCB)', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Informática', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Matemática', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Física', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Química', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Letras', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Educação Física', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Enfermagem', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Administração', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Ciências Contábeis', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Psicologia', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Ciências Biológicas', NOW(), NOW()),
(uuid_generate_v4(), 'Departamento de Ciências Sociais', NOW(), NOW());