CREATE TABLE usuario_cargo (
    id VARCHAR(36) PRIMARY KEY,
    usuario_id VARCHAR(36) REFERENCES usuario(id) ON DELETE CASCADE NOT NULL,
    cargo_id VARCHAR(36) REFERENCES cargo(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);