CREATE TABLE usuario_curso (
    id VARCHAR(36) PRIMARY KEY,
    usuario_id VARCHAR(36) REFERENCES usuario(id) ON DELETE CASCADE NOT NULL,
    curso_id VARCHAR(36) REFERENCES curso(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);